server:  
  port: ${port:9000}

spring:
  #profiles: production
  application:
    name: first-service
  data:
    mongodb:
      host: 192.168.0.39
      port: 27017
      database: test_db
      username: test 
      password: test1234!@
